---
title: "Lab_2"
author: "Abhinav Garg"
date: "1/19/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Part 1 

## 1. Load the Data 

```{r Load}
setwd("/Users/abhi/Documents/UW/Courses/Winter_Quarter_17/INFX_573/Week_3/Lab_2")
ratings <- read.csv("ratings.csv")
movies <- read.csv("movie.titles.csv")
dim(ratings)
users <- unique(ratings$userId)
d <- ratings[users,]
dim(d)

#Mean
mean(ratings$rating)



#Median 
median(ratings$rating)
#Mode
Mode <- function(x) {
    ux <- unique(x)
    ux[which.max(tabulate(match(x, ux)))]
}
Mode(ratings$rating)

#Plot histogram 

hist(ratings$rating)

```

## 2. Link the two datasets using movieid
```{r Link}
ix <- match(ratings$movieId, movies$movieId)

head(ratings$movieId)
head(movies$movieId[ix])

temp <- merge(ratings, movies, by = 'movieId')
head(temp)
```



## 3. Exploring Relationships I
```{r Explore I}
plot(ratings$year, ratings$rating)
boxplot(rating ~ year, data = ratings)
boxplot(rating ~ cut(year,breaks = 10), data = ratings)
```

## 4. Exploring Relationships II
```{r Explore II}
# a) Do the ratings vary by genre? Create a ‘comedy’ column and draw a box plot of ratings for comedy versus others:

ratings$comedy <- rep(F, nrow=ratings)
ratings$comedy[grep("comedy",ratings$genre,ignore.case = T)] <- T

boxplot(rating ~ comedy, data=ratings)

# b) Run a t-test to see if the differences in ratings for comedy versus non-comedy

t.test(ratings$rating, ratings$comedy)
```

## 5. Extra credit 
```{r Extra}
sorted_ratings <- ratings[order(-ratings$rating),]
top_ten_id<- head(sorted_ratings$movieId, n = 10)
top_ten_id
movies[top_ten_id,]$title

```

# Part 2 

```{r distributions}
# Examine several distributions
hist(rexp(1000))

hist(runif(1000,0,1))

hist(rpois(1000,0.5))


# Look at the distributions of sums of these samples

N <- 10000 # number of exponential draws
n.samp <- 25 # number of sums to take
M <- matrix(NA, nrow=N, ncol=n.samp) # create an empty matrix to fill with samples
for(j in 1:n.samp) M[,j] <- rexp(N) #generate the samples
hist(rowSums(M), freq = F) # plot a histogram of the sums across rows of our matrix M

curve(dnorm(x, mean(rowSums(M)), sd(rowSums(M))), min(rowSums(M)),
max(rowSums(M)), add=T, col="red", lwd=2)


# For Uniform 

for(j in 1:n.samp) M[,j] <- runif(N,0,1) #generate the samples
hist(rowSums(M), freq = F) # plot a histogram of the sums across rows of our matrix M

curve(dnorm(x, mean(rowSums(M)), sd(rowSums(M))), min(rowSums(M)),
max(rowSums(M)), add=T, col="red", lwd=2)


# For Poisson 

for(j in 1:n.samp) M[,j] <- rpois(N,0.5) #generate the samples
hist(rowSums(M), freq = F) # plot a histogram of the sums across rows of our matrix M

curve(dnorm(x, mean(rowSums(M)), sd(rowSums(M))), min(rowSums(M)),
max(rowSums(M)), add=T, col="red", lwd=2)
```
}